# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rapide < Formula
  desc "Lightweight CLI for Bullet Journal-style rapid logging."
  homepage "https://github.com/codevalve/rapide"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/codevalve/rapide/releases/download/v0.1.4/rapide_Darwin_x86_64.tar.gz"
      sha256 "3329e7bd118cb3f1a5e82bb32cc1df198e06cbbfb3528e17401f99ef8d38737c"

      def install
        bin.install "rapide"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/codevalve/rapide/releases/download/v0.1.4/rapide_Darwin_arm64.tar.gz"
      sha256 "51ef44006c7c8ed45dbd1957f41d190227fe801ef77f969fa43ab0c69a2a5b1a"

      def install
        bin.install "rapide"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/codevalve/rapide/releases/download/v0.1.4/rapide_Linux_x86_64.tar.gz"
      sha256 "80dbb71e186abd0b73ec277ba2e6578fa231eed0cbc78f03fcf6ebc7a8d94f8f"
      def install
        bin.install "rapide"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/codevalve/rapide/releases/download/v0.1.4/rapide_Linux_arm64.tar.gz"
      sha256 "ebb28783a9f7d0b3f2fe558a6c4919773a5bbc6e1c516cf8129438f63934af95"
      def install
        bin.install "rapide"
      end
    end
  end
end
