# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rapide < Formula
  desc "Lightweight CLI for Bullet Journal-style rapid logging."
  homepage "https://github.com/codevalve/rapide"
  version "3.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/codevalve/rapide/releases/download/v3.0.2/rapide_Darwin_x86_64.tar.gz"
      sha256 "6882db6ffe8609ad8f02f173fc1865cc5bd97718e1f636c17f37a698bfb938c0"

      define_method(:install) do
        bin.install "rapide"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/codevalve/rapide/releases/download/v3.0.2/rapide_Darwin_arm64.tar.gz"
      sha256 "153fc33b8794434a916bd499744e96883401851d280505553cb36a2fc28954c2"

      define_method(:install) do
        bin.install "rapide"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/codevalve/rapide/releases/download/v3.0.2/rapide_Linux_x86_64.tar.gz"
      sha256 "94937b1e13d9df809ceb536d91b53e49476d043aad43401aa1a2d50b53437af1"
      define_method(:install) do
        bin.install "rapide"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/codevalve/rapide/releases/download/v3.0.2/rapide_Linux_arm64.tar.gz"
      sha256 "44887e6a0f4fe9851dfd2965e37f52adfcb2df7b74644513f6600cb6f2b32297"
      define_method(:install) do
        bin.install "rapide"
      end
    end
  end
end
